"""empty message

Revision ID: 02327a25ce69
Revises: 03ed35991449
Create Date: 2024-06-27 18:39:17.349077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02327a25ce69'
down_revision = '03ed35991449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_address', 'address', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_address', type_='foreignkey')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###
